on:
  push:
    branches:
      - master
    tags-ignore:
      - '**'
jobs:
  version-bump-and-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Version bump + Generate changelog
        run: npx standard-version
